#!/usr/bin/env node
/**
 * Writes `public/sitemap.xml` and `public/robots.txt`.
 *
 *   npm run make:seo
 *
 * Both are generated from one list of routes and from `BRAND.url` in
 * `src/data/site.ts`, so they cannot drift from the site. **Set your real
 * domain there before running this** — a sitemap full of kmproductions.com
 * tells a search engine to go and index somebody else's website.
 *
 * `/book` is listed but `/admin` and the confirmation are not: one is an
 * internal console and the other is somebody's private receipt.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');

const site = await readFile(join(root, 'src/data/site.ts'), 'utf8');
const url = site.match(/url:\s*'([^']+)'/)?.[1] ?? 'https://kmproductions.com';
const origin = url.replace(/\/+$/, '');

const PLACEHOLDER = 'https://kmproductions.com';

/** priority is a hint, not a promise. Booking and the work rank highest. */
const ROUTES = [
  { path: '/', priority: '1.0', changefreq: 'weekly' },
  { path: '/real-estate', priority: '0.9', changefreq: 'monthly' },
  { path: '/portfolio', priority: '0.9', changefreq: 'weekly' },
  { path: '/book', priority: '0.9', changefreq: 'monthly' },
  { path: '/services', priority: '0.8', changefreq: 'monthly' },
  { path: '/commercial', priority: '0.8', changefreq: 'monthly' },
  { path: '/about', priority: '0.6', changefreq: 'yearly' },
  { path: '/contact', priority: '0.7', changefreq: 'yearly' },
  { path: '/faq', priority: '0.6', changefreq: 'monthly' },
  { path: '/privacy', priority: '0.2', changefreq: 'yearly' },
  { path: '/terms', priority: '0.2', changefreq: 'yearly' },
];

/** Never indexed: an internal console, and a page that is one person's receipt. */
const DISALLOW = ['/admin', '/book/confirmed'];

const today = new Date().toISOString().slice(0, 10);

const sitemap =
  '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
  ROUTES.map(
    (r) =>
      '  <url>\n' +
      `    <loc>${origin}${r.path === '/' ? '/' : r.path}</loc>\n` +
      `    <lastmod>${today}</lastmod>\n` +
      `    <changefreq>${r.changefreq}</changefreq>\n` +
      `    <priority>${r.priority}</priority>\n` +
      '  </url>',
  ).join('\n') +
  '\n</urlset>\n';

const robots =
  '# KM Productions\n' +
  '# Generated by scripts/make-seo.mjs — run `npm run make:seo` to rebuild.\n\n' +
  'User-agent: *\n' +
  'Allow: /\n' +
  DISALLOW.map((d) => `Disallow: ${d}`).join('\n') +
  '\n\n' +
  `Sitemap: ${origin}/sitemap.xml\n`;

await writeFile(join(root, 'public/sitemap.xml'), sitemap, 'utf8');
await writeFile(join(root, 'public/robots.txt'), robots, 'utf8');

console.log(`\npublic/sitemap.xml — ${ROUTES.length} routes`);
console.log(`public/robots.txt  — ${DISALLOW.length} paths kept out of search`);
console.log(`Origin: ${origin}\n`);

if (origin === PLACEHOLDER) {
  console.log('⚠  That origin is still the placeholder.');
  console.log('   Set your real domain as `url` in src/data/site.ts and run this again,');
  console.log('   or these files will point search engines at a domain you do not own.\n');
}
